name: Ticket refinement

on:
  issues:
    types: [labeled]

jobs:
  format:
    runs-on: ubuntu-latest
    container: node:22
    steps:
      - name: Fetch code
        run: |
          git clone "$(echo ${{github.server_url}}/${{github.repository}}.git | sed s%://%://${{github.token}}@% )" .
          git checkout ${{ github.event.repository.default_branch }}

      - name: Refine ticket
        run: npx -y -p @ztimson/ai-agents@latest refine
        env:
          AI_HOST: anthropic
          AI_MODEL: claude-sonnet-4-5
          AI_TOKEN: ${{ secrets.ANTHROPIC_TOKEN }}
          GIT_HOST: ${{ github.server_url }}
          GIT_OWNER: ${{ github.repository_owner }}
          GIT_REPO: ${{ github.event.repository.name }}
          GIT_TOKEN: ${{ secrets.ASSISTANT_TOKEN }}
          TICKET: ${{ github.event.issue.number }}
